# 1. numpy

- 1.1 `var_name = np.arange()` : numpy에서의 range => **실수 계산 가능**
- 1.2` var_name = np.array()` : 배열 안 모든 데이터들이 통일됨. => **연산에 용이**
- 1.3 `print(var_name.shape)` : 배열의 형태를 튜플로 반환 
- 1.4 `print(var_name.dtype)` : int, float, complex등 **데이터 타입**을 알려줌.

### 1.1 np.arrange : 실수형태에서의 range 계산 가능

In [155]:
import numpy as np

my_array = np.arange(1000000)

%timeit my_array2 = my_array * 2  

2.89 ms ± 276 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [156]:
# 1-1-1. list complelation
# %timeit 주피터에서 실행에 걸리는 시간 계산 

my_list = list(range(1000000))

%timeit my_list2 = [i * 2 for i in my_list] 

57.8 ms ± 3.83 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


### 1.2 np.array  : 배열 안 모든 데이터들이 통일됨.

In [57]:
# 1.2 np.array  : 배열 안 모든 데이터들이 통일됨.

a = [
    [1,1.2,3],
    [-123,123,0]
]

# 변수안에 넣기
data= np.array(a)
print(data)

[[   1.     1.2    3. ]
 [-123.   123.     0. ]]


In [12]:
# 0차원 : 스칼라 (단일 데이터로 곱셈을 했을때 같은 배열로)
# 1차원 : 벡터 
# 2차원 : 메트릭스(행렬) 
# 3차원: 텐서

#print(data * 10)

print(data + 10) #concatenation으로 연산

[[  11.    11.2   13. ]
 [-113.   133.    10. ]]


### 1.3 print(var_name.shape) : 배열의 형태를 튜플로 반환 => 몇차원의 배열인지
### 1.4 print(var_name.dtype) : int, float, complex등 데이터 타입을 알려줌.

In [13]:
# shape : 2 * 3의 2차원 배열 (배열의 형태를 튜플로 반환)
print(data.shape)

# dtype : data의 세부 데이터에 대한 내용 (실수라는 정보 전달) / bit가 길면 길수록 넓은 범위로 쓸 수 있음.
print(data.dtype)

(2, 3)
float64


# 2. ndarray 생성하기
- 파이썬의 list와 유사 (차이점 : 콤마(,) 사용 인덱싱, 슬라이싱 가능)
    - 2.1 `print(var_name.ndim)` : 배열의 차원 수 or 배열의 축 수 => 몇 차원
    - 2.2 `print(var_name.shape)` : . n행과 m열의 행렬의 경우 (n,m) 형태의 튜플로 반환
    - 2.3 `np.zeros(()) == np.empty(())` : ndarray에서 0의 배열 만들기

In [165]:
# 1) 
data1 = [1,2,3,4,5]
arr1 = np.array(data1)
#arr1
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [20]:
# 2) ndarray : 콤마, 인덱싱 사용 가능
arr2 = np.array([[1.1, 2.2],[3.3, 4.4]])
print(arr2)
print(type(arr2))

[[1.1 2.2]
 [3.3 4.4]]
<class 'numpy.ndarray'>


In [167]:
data2 = [[1.1,2.2],[3.3,4.4]]
arr2 = np.array(data2)
print(arr2)
print(type(arr2))

[[1.1 2.2]
 [3.3 4.4]]
<class 'numpy.ndarray'>


In [22]:
# 2.1 print(var_name.ndim) : 배열의 차원 수 or 배열의 축 수

print(arr1.ndim)
print(arr2.ndim)

# 2.2 print(var_name.shape) : . n행과 m열의 행렬의 경우 (n,m) 형태의 튜플로 반환

print(arr1.shape)
print(arr2.shape)

1
2
(5,)
(2, 2)


In [177]:
# 2.3 ndarray에서 0의 배열 만들기 : np.zeros(()) == np.empty(())

print(np.zeros(10)) #print([0] * 10)

print(np.zeros((5,5))) # 5 * 5 shape으로 0의 배열을 만들어줌.

print(np.zeros((2,2,2)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [174]:
a = np.empty((2,2,2)) # 2 * 3 shape으로 0의 배열을 만들어줌. (2개의 배열과 2개의 행 2개의 열로 되어 있음.)

print(a.ndim)

3


In [32]:
print(np.arange(0,10))

[0 1 2 3 4 5 6 7 8 9]


# 3. ndarray 자료형
- 3.1 `var_name = np.array(dtype = np.int64)` => int64로 데이터 타입 변경 : 데이터 타입 직접 변경
   - 3.1.1 `var_name.astype(np.int64)` : 형변환하는 함수 이용 

In [180]:
# 3-1 dtype 확인
arr1 = np.array([1,2,3], dtype = np.float64)
arr2 = np.array([1,2,3], dtype = np.int32)

print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [38]:
arr1 = np.array([1,2,3]) #ndim : 1차원, shape (,3) 튜플로 반환
print(arr1.dtype)

# 3-2 astype() : 형변환하는 내장함수
float_arr1 = arr1.astype(np.float64)
print(float_arr1)
print(float_arr1.dtype)

int64
[1. 2. 3.]
float64


In [39]:
arr2 = np.array([1.1,2.2,3.3])
print(arr2.dtype)

int_arr2 = arr2.astype(np.int64)
print(arr2)
print(arr2.dtype)

float64
[1.1 2.2 3.3]
float64


# 4. 연산
- 산술 연산 : 같은 위치에 있는 숫자끼리 (+ - * /) 
- 비교 연산 : True or False 값으로 비교 결과 나타남.

In [191]:
arr = np.array(([1,2,3],[4,5,6])) # ndim : 2차원, shape (2,3) 행열 
print(arr)

# 4. 산술연산
# 4-1 곱셈 : 같은 위치에 있는 숫자끼리 곱
print(arr * arr) 

# 4-2 뎃셈 : 
print(arr + arr)

# 4-3 나누기
print(1 /arr)

# 4-4 제곱
print(arr ** 3)

[[1 2 3]
 [4 5 6]]
[[ 1  4  9]
 [16 25 36]]
[[ 2  4  6]
 [ 8 10 12]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[  1   8  27]
 [ 64 125 216]]


In [190]:
# 4-5 비교 연산 (각각의 위치를 비교)

arr2 = np.array([[3,2,1],[1,2,3]])

# print(arr2.ndim) #2차원
# print(arr2.shape) #(2,3) 행렬

print(arr)
print(arr2)

print(arr > arr2)
print(arr == 3)

[[1 2 3]
 [4 5 6]]
[[3 2 1]
 [1 2 3]]
[[False False  True]
 [ True  True  True]]
[[False False  True]
 [False False False]]


# 5. 색인(인덱싱)과 슬라이싱
- 원하는 값을 뽑아내거나 범위를 지정하여 뽑아내고 싶을때
    - 5.1 인덱싱 :
        - 1차원 : arr[5]
        - 2차원 : arr[1][1] == arr[1,1]
        - 3차원 : arr[1][1][1] == arr[1,1,1]
    - 5.2 numpy의 슬라이싱: 원하는 위치의 데이터를 바꿈 => 원본까지 데이터가 바뀜.
        - 슬라이싱으로 인덱싱 : ex) arr3d[0, 1: ,2:] => 0인덱스의 1,2번째의 2번째 데이터들

In [193]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [194]:
print(arr[7])

print(arr[2:5])

7
[2 3 4]


In [69]:
# 4-2-1 numpy에서의 슬라이싱 : 슬라이싱해서 그 위치의데이터를 바꿀 수 있음. (원본까지 바뀜)

arr[2:5] = 10
print(arr)

[ 0  1 10 10 10  5  6  7  8  9]


In [72]:
# 4-2-2 python에서의 슬라이싱 : 팝을 해도 원본은 바뀌지 않음. 

py_list = [1,2,3,4,5]
py_list[2:3].pop
print(py_list)

[1, 2, 3, 4, 5]


In [196]:
# 4-1-1 2차원에서의 인덱싱

arr = np.array([[1,2,3],[4,5,6]])
# print(arr.ndim)
# print(arr.shape)
print(arr)

[[1 2 3]
 [4 5 6]]


In [197]:
print(arr[0][0])
print(arr[1,2])

1
6


In [199]:
# 4-1-2 3차원에서의 인덱싱

arr3d = np.array([[[1,2,3],[4,5,6],[7,8,9]], 
         [[11,12,13],[14,15,16],[17,18,19]], 
         [[11,22,33],[44,55,66],[77,88,99]]])

# print(arr3d.ndim)
# print(arr3d.shape)

print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[11 22 33]
  [44 55 66]
  [77 88 99]]]


In [82]:
print(arr3d[2][0][1])
print(arr3d[2,0,1])

22
22


In [86]:
arr3d[0, 1: ,2:] #범위를 나타낸다는 점!

array([[6],
       [9]])

In [87]:
arr3d[0, 1: ,2:] = 9999
print(arr3d)

[[[   1    2    3]
  [   4    5 9999]
  [   7    8 9999]]

 [[  11   12   13]
  [  14   15   16]
  [  17   18   19]]

 [[  11   22   33]
  [  44   55   66]
  [  77   88   99]]]


# 6. boolean 값으로 선택
- 특정 조건에 맞는 데이터를 골라낼때 불리언값 활용
    - 1) var_name == '문자' : boolean으로 알려줌 (true or false)
    - 2) key or value값에 접근 : indexing or slicing
        - `print(data[names == 'hong',1]) => 1인덱스 출력`
        - `print(data[names == 'hong', :1]) => 슬라이싱 0인덱스까지`       
    - 3) condition : 변수에 저장해서 접근
         - `cond = names == 'hong'`
         - `data[cond]`

In [202]:
names = np.array(['hong','kim','hong','kim'])

data = np.array([['math', 60],['math', 90],['eng', 70],['eng', 50]])

# print(data.shape)
# print(data.ndim)
# print(data)

(4, 2)
2
[['math' '60']
 ['math' '90']
 ['eng' '70']
 ['eng' '50']]


In [90]:
# 5-1 == bloolean 값으로 알려줌.

names == 'hong'

array([ True, False,  True, False])

In [92]:
# data[[True, False, True, False]]
data[names == 'hong']

array([['math', '60'],
       ['eng', '70']], dtype='<U21')

In [98]:
# key or value값에 접근 : indexing or slicing

print(data[names == 'hong',1]) #1차원
print(data[names == 'hong', :1]) #2차원

['60' '70']
[['math']
 ['eng']]


In [100]:
# condition : 변수에 저장해서 접근

print(names != 'hong') 
print(~(names == 'hong')) 

[False  True False  True]
[False  True False  True]


In [203]:
cond = names == 'kim'
data[cond]

array([['math', '90'],
       ['eng', '50']], dtype='<U21')

In [204]:
cond = names == 'hong'
data[cond]

array([['math', '60'],
       ['eng', '70']], dtype='<U21')

# 7. 팬시 인덱싱

In [205]:
arr = np.zeros((8,4))

for i in range(8):
    arr[i] = i #행의 줄을 i로 바꿈
print(arr)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


In [132]:
# 6-1 팬시 인덱싱 : 원하는 행을 직접적으로 고를 수 있게끔 / 순서도 마음대로 가능
# 선언 : 리스트 안에 리스트 [[]]

arr[[4,3,0,5]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [5., 5., 5., 5.]])

In [110]:
arr[[-3, -1, -5]]

array([[5., 5., 5., 5.],
       [7., 7., 7., 7.],
       [3., 3., 3., 3.]])

In [139]:
arr = np.arange(32).reshape(8,4) # reshape : 배열을 변경할 때 사용 (1,31) -> (8,4) 바꿔줌
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [142]:
print(arr[[1, 5], [2, 3]])

[ 6 23]


In [144]:
arr[ [1, 5] ]  [:, [2, 3] ]

array([[ 6,  7],
       [22, 23]])

# 8. 배열 전치 
- 배열의 축을 바꾸는 것
- 선언 :
- 접근 :

In [122]:
arr = np.arange(15).reshape(3,5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [124]:
# 7-1 배열 전치 : X축과 y축이 바뀜 => 행렬의 곱셈 가능
print(arr.T)

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [127]:
# 7-2 행렬에서의 곱 (행렬의 내적)

arr @ arr.T

print(np.dot(arr, arr.T))

[[ 30  80 130]
 [ 80 255 430]
 [130 430 730]]


# 9. numpy 함수

In [146]:
# 8-1

samples = np.random.standard_normal(size = (3,3))
print(samples)

[[-1.34493883  1.31258162 -0.57365478]
 [-0.2952962  -0.25816627  0.25678137]
 [-2.41521699 -1.04398147  0.44255559]]


In [148]:
# 8-2

# nan : 숫자가 아니라는 뜻 (음수는 루트를 씌울 수 없으니)

arr1 = np.sqrt(samples) # np.sqrt (루트)
print(arr1)

[[       nan 1.14567955        nan]
 [       nan        nan 0.506736  ]
 [       nan        nan 0.66524852]]


C:\Users\1-17\AppData\Local\Temp\ipykernel_1816\3151002730.py:3: RuntimeWarning: invalid value encountered in sqrt
  arr1 = np.sqrt(samples)


In [149]:
arr2 = np.abs(samples) #abs : 절대함수로 바꿔주는 함수 (음수 -> 양수)
print(arr2)

[[1.34493883 1.31258162 0.57365478]
 [0.2952962  0.25816627 0.25678137]
 [2.41521699 1.04398147 0.44255559]]


In [150]:
# 8-4 isnan : true or false 값으로 어디가 nan인지 알려줌.

np.isnan(arr1)

array([[ True, False,  True],
       [ True,  True, False],
       [ True,  True, False]])